### ISSUE TITLE
Adding RSS/Atom feeds

### ISSUE THREAD

**Issue by pfefferle** [aaronpk/IndieNews#21]

**Comment by voxpelli** [comment]
:+1: on this – or that https://github.com/snarfed/granary/issues/31 gets done so there's a reliable `h-feed` to  `atom` conversion service within the community

**Comment by KillianKemps** [comment]
👍 It would really be nice to have RSS/Atom feeds.

**Comment by voxpelli** [comment]
@KillianKemps As https://github.com/snarfed/granary/issues/31has been fixed now you can now get this through that service: https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fnews.indieweb.org%2Fen Perhaps better to keep it as a separate service to make IndieNews itself more DRY?

What IndieNews maybe could do is to point to the Granary feeds and maybe use https://github.com/snarfed/granary/issues/53 if/when IndieNews starts supporting Pubsubhubbub so that the Atom feed would also get realtime updates.

**Comment by KillianKemps** [comment]
Great! Thank you for the link. I only hope that this service will not shutdown all of sudden.

**Comment by aaronpk** [comment]
Done in f3385ad346a455a8ecc7063e9245be21242c4dcf
