### ISSUE TITLE
Permalinks with trailing slash

### ISSUE THREAD

**Issue by chrisaldrich** [aaronpk/IndieNews#27]
This URL works (with trailing /):
https://news.indieweb.org/en/boffosocko.com/2016/12/28/homebrew-website-club-los-angeles-notes-december-28-2016/

While this 404s:
https://news.indieweb.org/en/boffosocko.com/2016/12/28/homebrew-website-club-los-angeles-notes-december-28-2016

Based on examples it would appear as if the behavior is dictated by whether or not the post is submitted with/without the trailing slash as some posts are the opposite of the above. (Compare: https://news.indieweb.org/en/aaronparecki.com/2016/12/26/3/ownyourgram-polling which resolves while adding a trailing slash causes a 404)

**Comment by aaronpk** [comment]
The concept of "trailing slash" doesn't really exist, other than some web servers will automatically redirect to a URL that ends in a slash if the URL entered is a folder. The URL either does or does not have a slash at the end, and they're two totally different URLs otherwise. 

Are you having trouble submitting the URL with/without the slash? Were you expecting it to work differently? I'm not quite sure what the problem is you're describing here.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/aaronpk/IndieNews/issues/27#issuecomment-269654139" class="u-in-reply-to"></a>I suppose I'm used to many CMSs auto-redirecting to the alternate version if it's mistyped. I only noticed because I apparently sent it one way, but used the alternate on my "syndicated" copy and the alternate 404d.

I agree that they're technically two different URLs, and hopefully a rare occurrence that most won't notice the subtle difference.
